# Use an official MySQL image as a base image
FROM mysql:8.0

# Set the root user password (change it to your preferred password)
ENV MYSQL_ROOT_PASSWORD=123456

# Set the database name (change it to your preferred database name)
ENV MYSQL_DATABASE=clinic_mgmt

# Copy the MySQL dump file into the container
COPY clinic_mgmt.sql /home/

# Expose port 3306 for MySQL
EXPOSE 3306
