apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql
    pod-template-hash: c5fb7887
  name: mysql-c5fb7887-zpvkm
  namespace: web
spec:
  clusterIP: 198.48.33.228
  clusterIPs:
  - 198.48.33.228
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql
    pod-template-hash: c5fb7887
  type: ClusterIP
