apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
  namespace: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: 3237/php_apache:k8s
        imagePullPolicy: IfNotPresent
        name: php-apache-rhsx5
        ports:
        - containerPort: 80
          protocol: TCP
